---
- name:  Display Cisco info
  hosts:  rtr1
  gather_facts: no

  tasks:
    # Assign hostname to the rtr1
    - name: Give Hostname to the Router
      cisco.ios.ios_config:
        commands: hostname Router1

    #Configure the Login banner for the cisco router - rtr1 
    - name: Configure the login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          This is my login banner
          Welcome to the Ansible Automation
          By the order of SebbyCorp!!!
        state: present

    # Configure the SNMP Server on rtr1
    - name: Configure SNMP Server
      cisco.ios.ios_snmp_server:
        config:
          communities:
          -   acl_v4: testACL
              name: mergedComm
              rw: true
          contact: contact updated using merged
          engine_id:
          -   id: AB0C5342FF0F
              remote:
                  host: 8.8.8.8
                  udp_port: 25
          groups:
          -   group: mergedGroup
              version: v3
              version_option: auth
          file_transfer:
                  access_group: test
                  protocol:
                  - ftp
          hosts:
          -   community_string: mergedComm
              host: 10.0.0.109
              informs: true
              traps:
              - msdp
              - stun
              - pki
              version: 2c
          -   community_string: mergedComm
              host: 10.0.0.109
              traps:
              - slb
              - pki
          password_policy:
          -   change: 3
              digits: 23
              lower_case: 12
              max_len: 24
              policy_name: MergedPolicy
              special_char: 32
              upper_case: 12
          -   change: 43
              min_len: 12
              policy_name: MergedPolicy2
              special_char: 22
              upper_case: 12
          -   change: 11
              digits: 23
              max_len: 12
              min_len: 12
              policy_name: policy3
              special_char: 22
              upper_case: 12
          traps:
              cef:
                  enable: true
                  inconsistency: true
                  peer_fib_state_change: true
                  peer_state_change: true
                  resource_failure: true
              msdp: true
              ospf:
                  cisco_specific:
                      error: true
                      lsa: true
                      retransmit: true
                      state_change:
                          nssa_trans_change: true
                          shamlink:
                              interface: true
                              neighbor: true
                  error: true
                  lsa: true
                  retransmit: true
                  state_change: true
              syslog: true
              tty: true
          users:
          -   acl_v4: '24'
              group: dev
              username: userPaul
              version: v1
        state: merged

    #set NameServers on rtr1
    - name: configure name servers
      cisco.ios.ios_system:
        name_servers:
        - 8.8.8.8
        - 8.8.4.4
        
    #Set Logging Information on rtr1
    - name: configure host logging
      cisco.ios.ios_logging:
        dest: host
        name: 10.0.0.109
        state: present

    # Set new NTP server and source interface
    - name: Configure NTP Server
      cisco.ios.ios_ntp:
        server: 8.8.8.8
        source_int: GigabitEthernet1
        logging: false
        state: present

    #Configure IP address on Interface G2 of rtr1
    - name: configure ip address on interface GigabitEthernet2
      cisco.ios.ios_config:
        lines:
        - ip address 10.0.1.109 255.255.255.0
        parents: interface GigabitEthernet2

    # Configure OSPFv2 Protocol on rtr1
    - name: Merge provided OSPF V2 configuration
      cisco.ios.ios_ospfv2:
        config:
          processes:
          - process_id: 1
            max_metric:
              router_lsa: true
              on_startup:
                time: 110
            areas:
            - area_id: '5'
              capability: true
              authentication:
                enable: true
            - area_id: '10'
              authentication:
                message_digest: true
              nssa:
                default_information_originate:
                  metric: 10
                translate: suppress-fa
              default_cost: 10
              filter_list:
              - name: test_prefix_in
                direction: in
              - name: test_prefix_out
                direction: out
            network:
              address: 10.0.0.0
              wildcard_bits: 0.0.0.255
              area: 5
            default_information:
              originate: true
            passive_interfaces:
              default: true
              interface:
                set_interface: False
                name:
                  - GigabitEthernet1
          - process_id: 200
            vrf: blue
            domain_id:
              ip_address:
                address: 10.0.0.109
            max_metric:
              router_lsa: true
              on_startup:
                time: 100
            auto_cost:
              reference_bandwidth: 4
            areas:
            - area_id: '10'
              capability: true
            distribute_list:
              acls:
              - name: 10
                direction: out
              - name: 123
                direction: in
        state: merged


    

    
    
    